Added a paragraph to the story and some ASCII art
udi251nikolei/MNXB01-learn pull request #2
Opened 2022-10-10 13:56 UTC by floridop

Added some content to your story. You are free to ask me to do any change you like before approving!

2022-10-14 17:24 UTC, udi251nikolei requested changes
Thanks for your contribution. I saw you have made some edits on my first draft. I've written instructions in the 2 comments I've provided on specific line I want changes.

2022-10-14 17:24 UTC, udi251nikolei commented on README.md
> +there lived a **rich** but _cruel_ king - The Coldran of Kor.
I'd like to follow up line 3 with line 4 after the comma.

2022-10-14 17:24 UTC, udi251nikolei commented on README.md
> +chance to hear his name spoken.
I don't want line 6 to be a separated from line 5. Follow up line 5 with line 6.

2022-10-15 16:10 UTC, floridop commented
Requested changes implemented in commit [0c7968b](https://github.com/udi251nikolei/MNXB01-learn/pull/2/commits/0c7968bc7c518222d3a9c9a6bbe699ff2ed4bf25)

2022-10-19 14:24 UTC, floridop commented
Hello! could you please check that you're fine with the changes and eventually merge?

2022-10-19 14:34 UTC, floridop commented
Information about merging when you're the release manager is in Tutorial 5 slides 78-82

2022-10-20 13:14 UTC, merged

2022-10-20 13:14 UTC, udi251nikolei commented
Merging completed

2022-10-21 09:45 UTC, floridop commented
I'll close this part of the homework, but if there is something else 
you're curious to try and I am available I'll be happy to test.